### ISSUE TITLE
BUG/Aide

### ISSUE THREAD

**Issue by YamiYugi047** [MaRoTheTroLLeR/UltimateAnnounce#1]
Bonjour;
J'ai télécharger votre plugin qui me semble convenir à mes attentes le seul problème que j'ai mis 2 messages mais il n'y a que le 1er qui s'affiche en permanence l'autre ne veut pas s'afficher.

Voici mon config.yml : http://pastebin.com/1zZtfFDc

Je vous remercie d'avance :)

**Comment by MaRoTheTroLLeR** [comment]
Bonjour,
je ne vois pas où est le problème là,
Je tourne sur mon serveur avec votre configuration et tout fonctionne correctement
pouvez-vous expliquer votre problème?

**Comment by YamiYugi047** [comment]
Bah quand je le met c'est toujours le premier message qui s'affiche jamais le 2nd :/

**Comment by YamiYugi047** [comment]
Alors ?

**Comment by YamiYugi047** [comment]
En plus je voudrais savoir comment sauter des lignes svp ?

**Comment by MaRoTheTroLLeR** [comment]
if you mean to remove the header and footer you can make it to '' in the confir
I dont know why you have this bug but it's not from the plugin, Sorry

**Comment by MaRoTheTroLLeR** [comment]
Ok, je ai trouvé votre problème!
Je vais fixer en quelques minutes :)

**Comment by YamiYugi047** [comment]
Ok et comment faire pour sauter des lignes entre les messages svp ?

**Comment by MaRoTheTroLLeR** [comment]
./uan space
il permet de basculer entre les lignes des messages

**Comment by YamiYugi047** [comment]
Sa oui mais je veut dire dans les messages pas entre le Header et footer je voudrais vraiment DANS le message ? Et si on fait une configuration dans le fichier config comment donc faire les espaces ?
